### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by VatsaPuranam**

### CODE REVIEW

**Comment by wiebecoding** [comment]
Vatsa added his own change.

**Comment by VatsaPuranam** [comment]
Just to test, I wrote, "//Srivatsa Test Comment" in the ReadME file of my branch during class. Other than this and adding my name to the people to the list of names on the README on main, I did not make any other changes.

**Comment by VatsaPuranam** [comment]
Hope this isn't any issue

**Comment by wiebecoding** [comment]
@VatsaPuranam You are all good.

**Pull request closed without merging**
